### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by lluc**
Fix french translation ( by a french man, fan of railways and open data ... )     ;-)

### CODE REVIEW

**Comment by pstorch** [comment]
@lluc great, thanks :+1:

**Comment by pstorch** [comment]
@lluc I just found out that the french translation file was missing some texts. I added them now from the default english file. If you want to contribute some more, your help is very appreciated.

**Comment by lluc** [comment]
OK, I'm going to watch it ....

**Comment by lluc** [comment]
... I saw it. There are many sentences : it will take some times, but it will be OK.
-------
Es ist ein gross Arbeit, aber es wird gut gehen.  :-)

**Pull request merged**
